CREATE TABLE employees(id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 START 1),
           firstname text NOT NULL,
	   	   lastname text NOT NULL,
	   	   age int NOT NULL,
           title text NOT NULL, 
           location_id int NOT NULL,
           date_added date NOT NULL DEFAULT current_timestamp, 
	   FOREIGN KEY(location_id) REFERENCES offices(id));

INSERT INTO employees(firstname, lastname, age, title, location_id) VALUES('Rudolph','Reindeer', 23, 'Lead Reindeer', 1);
INSERT INTO employees(firstname, lastname, age, title, location_id) VALUES('Dasher', 'Reindeer', 24, 'Junior Reindeer', 1);
INSERT INTO employees(firstname, lastname, age, title, location_id) VALUES('Prancer','Reindeer', 25, 'Junior Reindeer', 2);
INSERT INTO employees(firstname, lastname, age, title, location_id) VALUES('Vixen',  'Reindeer', 28, 'Associate Reindeer', 2);
INSERT INTO employees(firstname, lastname, age, title, location_id) VALUES('Comet',  'Reindeer', 32, 'Associate Reindeer', 3);
INSERT INTO employees(firstname, lastname, age, title, location_id) VALUES('Cupid',  'Reindeer', 35, 'Senior Reindeer', 3);
INSERT INTO employees(firstname, lastname, age, title, location_id) VALUES('Dancer', 'Reindeer', 37, 'Senior Reindeer', 4);
INSERT INTO employees(firstname, lastname, age, title, location_id) VALUES('Donner', 'Reindeer', 38, 'Co-Captain', 4);
INSERT INTO employees(firstname, lastname, age, title, location_id) VALUES('Blitzen','Reindeer', 43, 'Co-Captain', 5);
